### ISSUE TITLE
Уведомление о счете за электроэнергию

### ISSUE THREAD

**Issue by RykovDC** [lizardsystems/hass-tnse#2]
Прошу помочь. Почему система пишет, что триггер не определен? 
![image](https://github.com/lizardsystems/hass-tnse/assets/139807719/dbfcf2f8-c534-424c-8282-5b95e3106b84)

**Comment by vzagorovskiy** [comment]
Весь yaml покажите, вот рабочий пример
```yaml
alias: "Мой Газ: Уведомление о счете за газ"
description: Уведомление о счете за газ от сервиса Мой Газ
trigger:
  - platform: event
    event_type: mygas_get_bill_completed
condition: []
action:
  - service: telegram_bot.send_document
    data:
      authentication: digest
      parse_mode: markdown
      url: "{{trigger.event.data.url}}"
      caption: >-
        Счет за газ для {{device_attr(trigger.event.data.device_id,
        'name_by_user') or  device_attr(trigger.event.data.device_id, 'name') }}
        за {{trigger.event.data.date}}
  - service: notify.persistent_notification
    data:
      message: >-
        Скачать счет для  [{{device_attr(trigger.event.data.device_id,
        'name_by_user') or  device_attr(trigger.event.data.device_id, 'name')
        }}]({{trigger.event.data.url}}) за {{trigger.event.data.date}}.
      title: >-
        Счет за газ для {{device_attr(trigger.event.data.device_id,
        'name_by_user') or  device_attr(trigger.event.data.device_id, 'name') }}
        за {{trigger.event.data.date}}
mode: single

```
